# Generated by Django 4.0.3 on 2023-07-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='webhook',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='webhook',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
